### PR TITLE
Analysis

### PR DESCRIPTION
**Pull request by an-ju**
- Added a page for activities.
- Added a page for inferred meetings.

### CODE REVIEW

**Comment by adnanhemani** [comment]
One feature request: have the name of the Pivotal Tracker project that generated the meeting show in the meetings page. Without it, it's hard to tell which team is associated with which meeting.

**Comment by adnanhemani** [comment]
Wait, also now that I think of this, the Activity.infer_meeting doesn't actually segregate activities per Pivotal Tracker team. So in this way, if another team starts a meeting before 1hour before the end of another team's meeting, this will just group all of them together into one meeting. This isn't the intended functionality of this feature.

**Comment by an-ju** [comment]
This is a quick solution to see the meetings.  It is true that this does not handle overlaps, but my assumption is that this won't be a big issue.  As for showing the team's name, that can't be done without external input, which wouldn't add more complexity.  So I think for this simple solution, we don't need that much.

**Comment by an-ju** [comment]
My plan is to merge and deploy this one, so we can see how the inferences do.  Then we can make it better by adding more features and handling more scenarios.

**Review by adnanhemani — APPROVED** [review]

**Pull request merged**
